//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BestScheduleEntities : DbContext
    {
        public BestScheduleEntities()
            : base("name=BestScheduleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConstraintsTask> ConstraintsTask { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<HoursNotActivityofRoute> HoursNotActivityofRoute { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<TaskInRoute> TaskInRoute { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TasksToCustomers> TasksToCustomers { get; set; }
    }
}
