//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.HoursNotActivityofRoute = new HashSet<HoursNotActivityofRoute>();
            this.TasksToCustomers = new HashSet<TasksToCustomers>();
        }
    
        public int IdRoute { get; set; }
        public Nullable<System.DateTime> DateToRoute { get; set; }
        public string IdCustomers { get; set; }
        public Nullable<System.DateTime> StartDateToRoute { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string nameRoute { get; set; }
    
        public virtual customers customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoursNotActivityofRoute> HoursNotActivityofRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksToCustomers> TasksToCustomers { get; set; }
    }
}
