//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksToCustomers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TasksToCustomers()
        {
            this.ConstraintsTask = new HashSet<ConstraintsTask>();
            this.TaskInRoute = new HashSet<TaskInRoute>();
        }
    
        public int IdTasksToCustomers { get; set; }
        public int IdTasks { get; set; }
        public string IdCustomers { get; set; }
        public int IdRoute { get; set; }
        public System.DateTime Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstraintsTask> ConstraintsTask { get; set; }
        public virtual customers customers { get; set; }
        public virtual Route Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskInRoute> TaskInRoute { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
